ESP 1.19

diff --git a/config/makeEnv b/config/makeEnv
--- a/config/makeEnv
+++ b/config/makeEnv
@@ -55,15 +55,19 @@ if [ -f /bin/uname -o -f /usr/bin/uname \
 	if [ -f /bin/uname ]; then
 		os="`/bin/uname -s`"
 		rl="`/bin/uname -r`"
+		mt="`/bin/uname -m`"
 	elif [ -f /usr/bin/uname ]; then
 		os="`/usr/bin/uname -s`"
 		rl="`/usr/bin/uname -r`"
+		mt="`/usr/bin/uname -m`"
 	elif [ -f /bin/uname.exe ]; then
 		os="`/bin/uname.exe -s`"
 		rl="`/bin/uname.exe -r`"
+		mt="`/bin/uname.exe -m`"
 	else
 		os="`/usr/bin/uname.exe -s`"
 		rl="`/usr/bin/uname.exe -r`"
+		mt="`/usr/bin/uname.exe -m`"
 	fi
 
 	ARCH=$os
@@ -78,17 +82,17 @@ fi
 #
 if [ "$ARCH" = Darwin ]; then
 	case "$rl" in
-	 9.*) MACOSX=10.5 ;;
-	10.*) MACOSX=10.6 ;;
-	11.*) MACOSX=10.7 ;;
-	12.*) MACOSX=10.8 ;;
-	13.*) MACOSX=10.9 ;;
-	14.*) MACOSX=10.10 ;;
-	15.*) MACOSX=10.11 ;;
-	16.*) MACOSX=10.12 ;;
-	17.*) MACOSX=10.13 ;;
-	18.*) MACOSX=10.14 ;;
-	19.*) MACOSX=10.15 ;;
+	14.*)   MACOSX=10.10 ;;
+	15.*)   MACOSX=10.11 ;;
+	16.*)   MACOSX=10.12 ;;
+	17.*)   MACOSX=10.13 ;;
+	18.*)   MACOSX=10.14 ;;
+	19.*)   MACOSX=10.15 ;;
+	20.1.*) MACOSX=11.0 ;;
+	20.2.*) MACOSX=11.1 ;;
+	20.3.*) MACOSX=11.2 ;;
+	20.4.*) MACOSX=11.3 ;;
+	20.5.*) MACOSX=11.4 ;;
 	esac
 fi
 
@@ -141,6 +145,11 @@ fi
 #
 if [ "$ARCH" = Darwin ]; then
 	CARCH=DARWIN64
+	if [ "$mt" = arm64 ]; then
+		CARCH=DARWINM1
+		echo "ERROR - ESP does not support Apple M1 yet!"
+		exit 1
+	fi
 else
 	CARCH=LINUX64
 fi
@@ -223,6 +232,7 @@ fi
 #
 # do we have a python?
 #
+echo
 PYTH=UNKNOWN
 if [ ! -n "$PYTHONINC" ]; then
 	PYTHONINC=UNKNOWN
@@ -233,25 +243,15 @@ fi
 pyt="`which python`"
 if [ -n "$pyt" ]; then
 	PYTH=python
+	echo "Info: Python exec $pyt found!"
 fi
 
-echo
 if [ "$PYTH" != UNKNOWN ]; then
 	if [ "$PYTHONINC" == UNKNOWN ]; then
 		pscr="\"from __future__ import print_function; import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('INCLUDEPY'))\""
 		pcmd="python -c $pscr"
 		eval PYTHINC=\`$pcmd\`
 
-		if [ -f "$PYTHINC/Python.h" ]; then
-			PYTHONINC=$PYTHINC
-			echo "Info: Python header $PYTHONINC/Python.h found!"
-		fi
-	fi
-
-	if [ "$PYTHONINC" == UNKNOWN ]; then
-		pscr="\"from __future__ import print_function; import distutils.sysconfig as sysconfig; print(sysconfig.get_path('platinclude'))\""
-		pcmd="python -c $pscr"
-		eval PYTHINC=\`$pcmd\`
 		if [ -f "$PYTHINC/Python.h" ]; then
 			PYTHONINC=$PYTHINC
 			echo "Info: Python header $PYTHONINC/Python.h found!"
@@ -312,23 +312,6 @@ if [ "$PYTH" != UNKNOWN ]; then
 
 	if [ "$PYTHONLIB" == UNKNOWN ]; then
 		pscr="\"from __future__ import print_function; import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))\""
-		pcmd="python -c $pscr"
-		eval plp=\`$pcmd\`
-
-		if [ -f "$plp/$pso" ]; then
-			PYTHONLIB="-L$plp -l$pllb"
-			echo "Info: Python library $plp/$pso found!"
-		elif [ -f "$plp/$pdy" ]; then
-			PYTHONLIB="-L$plp -l$pllb"
-			echo "Info: Python library $plp/$pdy found!"
-		#elif [ -f "$plp/$plb" ]; then
-		#	PYTHONLIB="-L$plp -l$pllb"
-		#	echo "Info: Python library $plb found!"
-		fi
-	fi
-
-	if [ "$PYTHONLIB" == UNKNOWN ]; then
-		pscr="\"from __future__ import print_function; import distutils.sysconfig as sysconfig; print(sysconfig.get_path('platstdlib'))\""
 		pcmd="python -c $pscr"
 		eval plp=\`$pcmd\`
 
@@ -464,16 +447,16 @@ else
 fi
 if [ "$PYTH" != UNKNOWN ]; then
 	if [ "$PYTH" != ERROR ]; then
-		echo "export PYTHONINC="$PYTHONINC             >> ../ESPenv.sh
+		echo "export PYTHONINC=\""$PYTHONINC\"         >> ../ESPenv.sh
 		echo "export PYTHONLIB=\""$PYTHONLIB\"         >> ../ESPenv.sh
 	else
-		echo "#export PYTHONINC="$PYTHONINC            >> ../ESPenv.sh
+		echo "#export PYTHONINC=\""$PYTHONINC\"        >> ../ESPenv.sh
 		echo "#export PYTHONLIB=\""$PYTHONLIB\"        >> ../ESPenv.sh
 	fi
-	if [ -z "$PYTHONPATH" ]; then
-		echo "export PYTHONPATH=$BASE/lib"               >> ../ESPenv.sh
+        if [ -z "$PYTHONPATH" ]; then
+		echo "export PYTHONPATH=$BASE/pyESP"           >> ../ESPenv.sh
 	else
-		echo "export PYTHONPATH=$BASE/lib":'$PYTHONPATH' >> ../ESPenv.sh
+		echo "export PYTHONPATH=$BASE/pyESP":'$PYTHONPATH' >> ../ESPenv.sh
 	fi
 fi
 if [ "$EFCOMP" != UNKNOWN ]; then
@@ -512,13 +495,12 @@ fi
 if [ "$TETGEN" != UNKNOWN ]; then
 	echo "export TETGEN=$TETGEN" >> ../ESPenv.sh
 else
-	echo "#export TETGEN=$HOME/Projects/TetGen/tetgen1.5.1" >> ../ESPenv.sh
+	echo "#export TETGEN=$HOME/Projects/TetGen/tetgen1.6.0" >> ../ESPenv.sh
 fi
 echo "#export AWAVE=$HOME/Projects/awave/awavemod.f"    >> ../ESPenv.sh
 if [ "$ARCH" = Darwin ]; then
 	echo "export SLUGS_START=\"open -a /Applications/Safari.app $BASE/SLUGS/Slugs.html\"" >> ../ESPenv.sh
-	echo "export CAPS_START=\"open -a /Applications/Safari.app $BASE/src/CAPS/pyCAPS/viewer/capsViewer.html\"" >> ../ESPenv.sh
-	echo "export ESP_START=\"open -a /Applications/Safari.app $BASE/ESP/ESP.html\""       >> ../ESPenv.sh
+	echo "export ESP_START=\"open -a /Applications/Safari.app;sleep 1;open -a /Applications/Safari.app $BASE/ESP/ESP.html\""       >> ../ESPenv.sh
 	echo "export WV_START=\"open -a /Applications/Safari.app $BASE/wvClient/wv.html\""    >> ../ESPenv.sh
 else
 	echo "export SLUGS_START=\"firefox $BASE/SLUGS/Slugs.html\"" >> ../ESPenv.sh
@@ -541,16 +523,16 @@ else
 fi
 if [ "$PYTH" != UNKNOWN ]; then
 	if [ "$PYTH" != ERROR ]; then
-		echo "setenv PYTHONINC "$PYTHONINC             >> ../ESPenv.csh
+		echo "setenv PYTHONINC \""$PYTHONINC\"         >> ../ESPenv.csh
 		echo "setenv PYTHONLIB \""$PYTHONLIB\"         >> ../ESPenv.csh
 	else
-		echo "#setenv PYTHONINC "$PYTHONINC            >> ../ESPenv.csh
+		echo "#setenv PYTHONINC \""$PYTHONINC\"        >> ../ESPenv.csh
 		echo "#setenv PYTHONLIB \""$PYTHONLIB\"        >> ../ESPenv.csh
 	fi
 	if [ -z "$PYTHONPATH" ]; then
-		echo "setenv PYTHONPATH $BASE/lib"               >> ../ESPenv.csh
+		echo "setenv PYTHONPATH $BASE/pyESP"           >> ../ESPenv.csh
 	else
-		echo "setenv PYTHONPATH $BASE/lib":'$PYTHONPATH' >> ../ESPenv.csh
+		echo "setenv PYTHONPATH $BASE/pyESP":'$PYTHONPATH' >> ../ESPenv.csh
 	fi
 fi
 if [ "$EFCOMP" != UNKNOWN ]; then
@@ -589,13 +571,12 @@ fi
 if [ "$TETGEN" != UNKNOWN ]; then
 	echo "setenv TETGEN $TETGEN" >> ../ESPenv.csh
 else
-	echo "#setenv TETGEN $HOME/Projects/TetGen/tetgen1.5.1" >> ../ESPenv.csh
+	echo "#setenv TETGEN $HOME/Projects/TetGen/tetgen1.6.0" >> ../ESPenv.csh
 fi
 echo "#setenv AWAVE $HOME/Projects/awave/awavemod.f"    >> ../ESPenv.csh
 if [ "$ARCH" = Darwin ]; then
 	echo "setenv SLUGS_START \"open -a /Applications/Safari.app $BASE/SLUGS/Slugs.html\"" >> ../ESPenv.csh
-	echo "setenv CAPS_START \"open -a /Applications/Safari.app $BASE/src/CAPS/pyCAPS/viewer/capsViewer.html\"" >> ../ESPenv.csh
-	echo "setenv ESP_START \"open -a /Applications/Safari.app $BASE/ESP/ESP.html\""       >> ../ESPenv.csh
+	echo "setenv ESP_START \"open -a /Applications/Safari.app;sleep 1;open -a /Applications/Safari.app $BASE/ESP/ESP.html\""       >> ../ESPenv.csh
 	echo "setenv WV_START \"open -a /Applications/Safari.app $BASE/wvClient/wv.html\""    >> ../ESPenv.csh
 else
 	echo "setenv SLUGS_START \"firefox $BASE/SLUGS/Slugs.html\"" >> ../ESPenv.csh
